AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'lib/main.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'